---
- name: Install httpd 
  hosts: localhost
  tasks:
    - name: Install httpd service
      apt:
        name: apache2
        state: present
    - name: Start httpd service
      service:
        name: apache2
        state: started
        enabled: yes
      
